load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "registry",
    srcs = ["registry.go"],
    importpath = "github.com/MetalBlockchain/metalgo/graft/coreth/precompile/registry",
    visibility = ["//visibility:public"],
    deps = ["//graft/coreth/precompile/contracts/warp"],
)
