load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "proposermock",
    srcs = ["windower.go"],
    importpath = "github.com/MetalBlockchain/metalgo/vms/proposervm/proposer/proposermock",
    visibility = ["//visibility:public"],
    deps = [
        "//ids",
        "@org_uber_go_mock//gomock",
    ],
)
